version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_dostava
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: dostava
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
